Enabled support for rootcryptpass=xxxx boot option to set encrypted passwords

diff --git a/airootfs/etc/systemd/scripts/sysresccd-initialize b/airootfs/etc/systemd/scripts/sysresccd-initialize
--- a/airootfs/etc/systemd/scripts/sysresccd-initialize
+++ b/airootfs/etc/systemd/scripts/sysresccd-initialize
@@ -1,10 +1,10 @@
 #!/bin/sh
-logfile="/var/log/sysresccd-initialize.log"
-echo "$(date +%Y%m%d-%H%M%S) $0 Starting ..." > ${logfile}
+echo "$0 Starting ..."
+errcnt=0
 
 # Set a random root password by default
-SSHPASS1=$(openssl rand -base64 32)
-echo "root:${SSHPASS1}" | chpasswd > /dev/null 2>&1
+SSHPASS0=$(openssl rand -base64 32)
+echo "root:${SSHPASS0}" | chpasswd || echo "Failed to set a default random root password"
 
 # Process options passed on the boot command line
 for curopt in $(cat /proc/cmdline)
@@ -12,17 +12,39 @@ do
     case "${curopt}" in
       # Configure keyboard layout if requested in the boot command line
       setkmap\=*)
-          echo "Found option '${curopt}' in the boot command line" >> ${logfile}
+          echo "Found option '${curopt}' on the boot command line"
           SETKMAP=$(echo "${curopt}" | cut -f2 -d=)
           /sbin/loadkeys ${SETKMAP}
           mkdir -p /etc/sysconfig
           echo "XKEYBOARD=${SETKMAP}" > /etc/sysconfig/keyboard
           ;;
-      # Set the system root password and allow root login
+      # Set the system root password from a clear password
       rootpass\=*)
-          echo "Found option 'rootpass=******' in the boot command line" >> ${logfile}
+          SSHPASS1=$(echo "${curopt}" | cut -f2 -d=)
+          echo "Found option 'rootpass=******' on the boot command line"
+          if echo "root:${SSHPASS1}" | chpasswd --crypt-method SHA512
+          then
+              echo "Password successfully changed"
+          else
+              echo "Failed to change password"
+              errcnt=$((errcnt + 1))
+          fi
+          ;;
+      # Set the system root password from an encrypted password
+      # A password can be encrypted using a one-line python3 command such as:
+      # python3 -c 'import crypt; print(crypt.crypt("MyPassWord123", crypt.mksalt(crypt.METHOD_SHA256)))'
+      rootcryptpass\=*)
           SSHPASS2=$(echo "${curopt}" | cut -f2 -d=)
-          echo "root:${SSHPASS2}" | chpasswd > /dev/null 2>&1
+          echo "Found option 'rootcryptpass=******' on the boot command line"
+          if echo "root:${SSHPASS2}" | chpasswd --encrypted
+          then
+              echo "Password successfully changed"
+          else
+              echo "Failed to change password"
+              errcnt=$((errcnt + 1))
+          fi
           ;;
     esac
 done
+
+exit ${errcnt}
